# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BoringBudget < Formula
  desc "Local-first budgeting CLI with deterministic JSON contracts"
  homepage "https://github.com/guseducampos/boring-budget"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.2/boring-budget_0.1.2_darwin_amd64.tar.gz"
      sha256 "325e18dbf42ab79794f89c607648ea5ce18d7cc320310f4ccc9c530ad82b5207"

      def install
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.2/boring-budget_0.1.2_darwin_arm64.tar.gz"
      sha256 "07a9b34236e6f6b2d00811583b2d5ee979171fc44e25d23574ee1391d1ad768a"

      def install
        bin.install "boring-budget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.2/boring-budget_0.1.2_linux_amd64.tar.gz"
      sha256 "7795da1a50c9a7c59e8f70c08875f44be3e4c2731765599eb8096de38a8db7ff"
      def install
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.2/boring-budget_0.1.2_linux_arm64.tar.gz"
      sha256 "4e88055db11efa576967b52064c7d7a25d0a471c3e0fbf05272dff740204827c"
      def install
        bin.install "boring-budget"
      end
    end
  end

  test do
    system "#{bin}/boring-budget", "--help"
  end
end
