# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BoringBudget < Formula
  desc "Local-first budgeting CLI with deterministic JSON contracts"
  homepage "https://github.com/guseducampos/boring-budget"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.3/boring-budget_0.1.3_darwin_amd64.tar.gz"
      sha256 "9e5c6b35003816ed7f22f46293caa269dcb294f15323354e9fdd8eb7a81f8fc2"

      define_method(:install) do
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.3/boring-budget_0.1.3_darwin_arm64.tar.gz"
      sha256 "244379bb3c09aec39738499a8b2f57b16941fda85fe3fa3b11c90923f511c497"

      define_method(:install) do
        bin.install "boring-budget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.3/boring-budget_0.1.3_linux_amd64.tar.gz"
      sha256 "6fb3ebac8712d7744a009eba5e9526d4341516400230216fd5da3c87c8946cf1"
      define_method(:install) do
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.3/boring-budget_0.1.3_linux_arm64.tar.gz"
      sha256 "58ccd413814921a9439afc30f5fad4590910948d9cb2f398ac9f846401392fac"
      define_method(:install) do
        bin.install "boring-budget"
      end
    end
  end

  test do
    system "#{bin}/boring-budget", "--help"
  end
end
