# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BoringBudget < Formula
  desc "Local-first budgeting CLI with deterministic JSON contracts"
  homepage "https://github.com/guseducampos/boring-budget"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.1/boring-budget_0.1.1_darwin_amd64.tar.gz"
      sha256 "7a6bdc07cf05d69d9c244f3ced0c972ec62e78d7fa10e91c91e9be8f8f925b02"

      def install
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.1/boring-budget_0.1.1_darwin_arm64.tar.gz"
      sha256 "839fe4e4584b8d76a1117438458cc970ed912855744aa411a4e5d0e5570107af"

      def install
        bin.install "boring-budget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.1/boring-budget_0.1.1_linux_amd64.tar.gz"
      sha256 "8c45c61522694f6969b671916e7fab6e13c40bb116983c85501e41838fe4f9b9"
      def install
        bin.install "boring-budget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guseducampos/boring-budget/releases/download/v0.1.1/boring-budget_0.1.1_linux_arm64.tar.gz"
      sha256 "de860bdcd466ba0a7807919b7472f5284c5f39bc0630140498ad0abaa2db8198"
      def install
        bin.install "boring-budget"
      end
    end
  end

  test do
    system "#{bin}/boring-budget", "--help"
  end
end
